local d = require("config.defaults")

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("mako")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd([[bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown"]])
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd([[bash -c 'ln -sf /home/koes/Pictures/wallpapers/lighthouse2.jpg $HOME/.config/hypr/current_wallpaper && awww img /home/koes/Pictures/wallpapers/lighthouse2.jpg']])
    hl.exec_cmd("systemctl --user import-environment")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null")
    hl.exec_cmd("dbus-update-activation-environment --systemd")
    hl.exec_cmd(d.idlehandler)
    hl.exec_cmd("systemctl --user start gammastep.service")
    hl.exec_cmd("[workspace special:discord silent] vesktop --ozone-platform-hint=auto %U --enable-blink-features=MiddleClickAutoscroll")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("brightnessctl set 100%")
end)
