# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Environment Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
envd = HYPRCURSOR_THEME,rose-pine-hyprcursor
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_THEME,rose-pine-hyprcursor
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24
envd = QT_QPA_PLATFORM,wayland;xcb
envd = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
