#:schema https://yazi-rs.github.io/schemas/keymap.json

# Plugins
[[mgr.prepend_keymap]]
on   = "M"
run  = "plugin mount"
desc = "Mount manager"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# Shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = "<C-w>"
run  = "shell 'awww img %h --transition-type center --transition-fps 60 --transition-duration 2'"
desc = "Set hovered image as wallpaper"

[[mgr.prepend_keymap]]
on   = [ "c", "i" ]
run  = "shell 'wl-copy < %h'"
desc = "Copy file contents to the clipboard"

# Goto
[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/programming"
desc = "Go to ~/programming"

[[mgr.prepend_keymap]]
on   = [ "g", "." ]
run  = "cd ~/dotfiles"
desc = "Go to ~/dotfiles"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/Pictures/wallpapers"
desc = "Go to wallpapers"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/Pictures/screenshots"
desc = "Go to screenshots"
