#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio          = [ 1, 3, 4 ]
sort_by        = "natural"
sort_dir_first = true
linemode       = "size"
show_symlink   = true

[opener]
edit = [
  { run = "zeditor %s",       desc = "Zed",     for = "linux", orphan = true },
  { run = "${EDITOR:-vi} %s", desc = "$EDITOR", for = "unix",  block = true },
]
browser = [
  { run = "firefox-developer-edition %s", desc = "Firefox", for = "linux", orphan = true },
]

[[open.prepend_rules]]
mime = "application/pdf"
use  = [ "open", "browser", "reveal" ]

[[open.prepend_rules]]
mime = "text/html"
use  = [ "edit", "browser", "reveal" ]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
